### ISSUE TITLE
Missing documentation how to use

### ISSUE THREAD

**Issue by binlab** [gregdurham/vault-plugin-secrets-keycloak#1]
Great work, thanks!
Could you please provide some documentation on how to use it?

**Comment by gregdurham** [comment]
For sure. I’m sorry, i didn’t see this come through. Let me work on some!

**Comment by binlab** [comment]
Thanks!

**Comment by gregdurham** [comment]
Updated the readme with some documentation, hopefully this helps! Let me know what you think, I have some thoughts about how I would like to extend it, but may need to make it as another secrets plugin as it would use roles rather than just allowing the clientID to be passed into the creds route.
